# Generated by Django 5.2.6 on 2025-09-27 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servicio_id', models.IntegerField(choices=[(1, 'Agua'), (2, 'Luz'), (3, 'Gas')])),
                ('id_user', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateField()),
                ('periodo', models.DateField()),
                ('consumo_agua_m3', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('consumo_luz_kwh', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('consumo_gas_m3', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('consumo_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('torre', models.CharField(max_length=50)),
                ('propietario_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Morosidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factura_id', models.IntegerField()),
                ('cuenta', models.CharField(max_length=50)),
                ('emision', models.DecimalField(decimal_places=2, max_digits=10)),
                ('convenio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('morosidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('año', models.IntegerField()),
                ('monto_deuda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_registro', models.DateTimeField()),
                ('estado', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factura_id', models.IntegerField()),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateTimeField()),
                ('codigo_qr', models.TextField(blank=True, null=True)),
                ('referencia_transaccion', models.TextField(blank=True, null=True)),
                ('metodo_pago', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_alerta', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('fecha_alerta', models.DateTimeField()),
                ('estado', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='recursoConsumo.consumo')),
            ],
        ),
        migrations.AddField(
            model_name='consumo',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='recursoConsumo.departamento'),
        ),
        migrations.CreateModel(
            name='Medidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servicio_id', models.IntegerField(choices=[(1, 'Agua'), (2, 'Luz'), (3, 'Gas')])),
                ('codigo', models.CharField(max_length=15)),
                ('activo', models.BooleanField(default=True)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medidores', to='recursoConsumo.departamento')),
            ],
        ),
    ]
