# Generated by Django 5.2.6 on 2025-09-28 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursoConsumo', '0002_rename_año_morosidad_anio_remove_consumo_id_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='factura_id',
        ),
        migrations.AddField(
            model_name='alerta',
            name='morosidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='recursoConsumo.morosidad'),
        ),
        migrations.AddField(
            model_name='alerta',
            name='nivel_riesgo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='alerta',
            name='probabilidad',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='morosidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='consumo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='recursoConsumo.consumo'),
        ),
    ]
