# Generated by Django 5.2.6 on 2025-09-28 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursoConsumo', '0003_remove_pago_factura_id_alerta_morosidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='morosidad',
            name='factura_id',
        ),
        migrations.AlterField(
            model_name='pago',
            name='morosidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='recursoConsumo.morosidad'),
        ),
    ]
