# Generated by Django 5.2.6 on 2025-09-29 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursoConsumo', '0004_remove_morosidad_factura_id_alter_pago_morosidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morosidad',
            name='estado',
            field=models.CharField(default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='morosidad',
            name='monto_deuda',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
