# Generated by Django 5.2.6 on 2025-09-29 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recursoConsumo', '0005_alter_morosidad_estado_alter_morosidad_monto_deuda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumo',
            name='periodo',
        ),
        migrations.RemoveField(
            model_name='consumo',
            name='tipo_servicio_id',
        ),
    ]
