# Generated by Django 5.2.6 on 2025-09-29 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursoConsumo', '0006_remove_consumo_periodo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumo',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumos', to='recursoConsumo.departamento'),
        ),
    ]
