# Generated by Django 5.2.6 on 2025-10-04 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursoConsumo', '0007_alter_consumo_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='habitantes',
            field=models.IntegerField(default=1),
        ),
    ]
