# Generated by Django 5.2.6 on 2025-10-04 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursoConsumo', '0008_departamento_habitantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='morosidad',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='morosidades', to='recursoConsumo.departamento'),
        ),
    ]
